/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2023-04-30 15:00:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/workspace.edu/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/songproject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1612850415545L));
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/workspace.edu/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/songproject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("// opener관련 오류가 발생하는 경우 아래 주석을 해지하고, 사용자의 도메인정보를 입력합니다. (\"팝업API 호출 소스\"도 동일하게 적용시켜야 합니다.)\r\n");
      out.write("//document.domain = \"abc.go.kr\";\r\n");
      out.write("\r\n");
      out.write("function goPopup(){\r\n");
      out.write("\tlet openUrl = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jusoPopup.do\";\r\n");
      out.write("    var pop = window.open(openUrl,\"pop\",\"width=570,height=420, scrollbars=yes, resizable=yes\"); \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function jusoCallBack(roadFullAddr,roadAddrPart1,addrDetail,roadAddrPart2,engAddr, jibunAddr, zipNo, admCd, rnMgtSn, bdMgtSn\r\n");
      out.write("\t\t\t\t\t\t, detBdNmList, bdNm, bdKdcd, siNm, sggNm, emdNm, liNm, rn, udrtYn, buldMnnm, buldSlno, mtYn, lnbrMnnm, lnbrSlno, emdNo){\r\n");
      out.write("\tdocument.form.roadAddrPart1.value = roadAddrPart1;\r\n");
      out.write("\tdocument.form.roadAddrPart2.value = roadAddrPart2;\r\n");
      out.write("\tdocument.form.addrDetail.value = addrDetail;\r\n");
      out.write("\tdocument.form.zipNo.value = zipNo;\r\n");
      out.write("\tconsole.log(roadAddrPart1+\"/\"+roadAddrPart2);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"https://cdn.iamport.kr/v1/iamport.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.0.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/JoinPage.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t  <main id=\"main-holder\" class=\"container\">\r\n");
      out.write("\t\t<form action=\"JoinService.do\" name=\"form\" id=\"form\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t<article id=\"Contents\" class=\"joinPerson memberJoin\">\r\n");
      out.write("\t\t\t<h1 class=\"sign__title\">회원가입</h1>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 아이디 입력창 -->\r\n");
      out.write("\t\t\t\t<div class=\"input-box-wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-box\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" minlength=\"5\" id=\"userid\" name=\"user_id\" class=\"has-label\" value=\"\" maxlength=\"15\" autocomplete=\"\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"userid\">아이디 (5~15자 영문,숫자)</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"valid-text\">\r\n");
      out.write("\t\t\t\t\t<p id=\"msg_userid\" class=\"msg\"></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t<!-- 비밀번호 입력창 -->\r\n");
      out.write("\t\t\t<section class=\"sign-section passwd\">\r\n");
      out.write("\t\t\t\t<ul class=\"input-box-wrap\">\r\n");
      out.write("\t\t\t\t\t<li class=\"input-box\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" id=\"passwd\" name=\"user_pw\" minlength=\"5\" class=\"has-label\" value=\"\" autocomplete=\"new-password\" value={password} onChange={onChangePassword} >\r\n");
      out.write("\t\t\t\t\t\t<label for=\"passwd\">비밀번호<span>5-15자의 영문/숫자 또는 특수문자 조합</span></label>\r\n");
      out.write("\t\t\t\t\t\t{password  && (<span>{passwordMessage}</span>)}\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" id=\"changePasswdType\" class=\"password-view-btn\" onclick=\"\">표시</button>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"input-box\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" id=\"passwd2\" name=\"passwd2\" class=\"has-label\" value=\"\" minlength=\"8\" maxlength=\"16\"  value={passwordConfirm} onChange={onChangePasswordConfirm}>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"passwd2\">비밀번호 재입력</label>\r\n");
      out.write("\t\t\t\t\t\t{passwordConfirm ? (password === passwordConfirm ? <span>같음</span> : <span>다름</span>) : null}\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"valid-text\">\r\n");
      out.write("\t\t\t\t\t<p id=\"msg_passwd\" class=\"msg\"></p>\r\n");
      out.write("\t\t\t\t\t<p id=\"msg_passwd2\" class=\"msg\"></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t<!-- 이름 입력창 o-->\r\n");
      out.write("\t\t\t<section class=\"sign-section name\">\r\n");
      out.write("\t\t\t\t<div class=\"input-box-wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-box\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"usernm\" class=\"has-label\" name=\"user_name\" maxlength=\"20\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"usernm\">이름</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"valid-text\">\r\n");
      out.write("\t\t\t\t\t<p id=\"msg_usernm\" class=\"msg\"></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t<!-- nick네임 입력창 o-->\r\n");
      out.write("\t\t\t<section class=\"sign-section\">\r\n");
      out.write("\t\t\t\t<div class=\"input-box-wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-box\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"email\" class=\"has-label\" name=\"user_nick\" value=\"\" maxlength=\"50\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"email\">닉네임</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<!-- 주소 입력창 -->\r\n");
      out.write("\t\t\t<section class=\"sign-section address\">\r\n");
      out.write("\t\t\t\t<ul class=\"input-box-wrap\">\r\n");
      out.write("\t\t\t\t\t<li class=\"input-box\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"htel\">우편번호\r\n");
      out.write("\t\t\t\t\t\t<span><input type=\"text\" id=\"zipNo\" name=\"zipNo\" readonly style=\"width:100px\" value=\"\"></span>\r\n");
      out.write("\t\t\t\t\t    <span><input type=\"hidden\" id=\"confmKey\" name=\"confmKey\" value=\"\"  ></span>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\"  value=\"주소검색\" onclick=\"goPopup()\">\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"input-box\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"text\">도로명주소\r\n");
      out.write("\t\t\t\t\t\t\t<span><input type=\"text\" id=\"roadAddrPart1\" name=\"addr1\" style=\"width:70%\" readonly=\"readonly\" value=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span><input type=\"text\" id=\"roadAddrPart11\" name=\"roadAddrPart11\" readonly=\"readonly\" value=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"input-box\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"text\">상세주소\r\n");
      out.write("\t\t\t\t\t\t\t<span><input type=\"text\" id=\"addrDetail\" name=\"addr3\" style=\"width:40%\" readonly=\"readonly\" value=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span><input type=\"text\" id=\"roadAddrPart2\" name=\"addr2\"  style=\"width:40%\" readonly=\"readonly\" value=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t<!-- 휴대폰번호 입력창 o-->\r\n");
      out.write("\t\t\t<section class=\"sign-section\">\r\n");
      out.write("\t\t\t\t<ul class=\"input-box-wrap\">\r\n");
      out.write("\t\t\t\t\t<li class=\"input-box\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"htel\">휴대폰 <span>('-' 없이 입력하세요.)</span></label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"tel\" id=\"htel\" class=\"has-label\" name=\"user_phone\" value=\"\" maxlength=\"11\">\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\t\t\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"btnAction\" style=\"display: flex; justify-content: center;\">\r\n");
      out.write("\t\t\t<!-- fff230 -> c0c0c0 -->\r\n");
      out.write("\t\t\t\t<input type= \"submit\" class=\"btn btnType1 submit\" style=\"width: 80%;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</main>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("html {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("  height: 136%;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("  display: grid;\r\n");
      out.write("  justify-items: center;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  background-color: #3a3a3a;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main-holder {\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  height: 70%;\r\n");
      out.write("  display: grid;\r\n");
      out.write("  justify-items: center;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  border-radius: 7px;\r\n");
      out.write("  box-shadow: 0px 0px 5px 2px black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#error-msg-second-line {\r\n");
      out.write("  display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main-holder {\r\n");
      out.write("  width: 70%;\r\n");
      out.write("  height: 90%;\r\n");
      out.write("}\r\n");
      out.write("  </style>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/user/joinPage.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/user/joinPage.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/joinPage.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
