/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2023-06-20 00:36:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.board.entity.User_Result;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/workspace.edu/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ShimBeeSeo/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1612850415545L));
    _jspx_dependants.put("jar:file:/C:/eGovFrame-4.0.0/workspace.edu/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ShimBeeSeo/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.board.entity.User_Result");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>내 정보^오^</title>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\n");
      out.write("<meta content=\"\" name=\"keywords\">\n");
      out.write("<meta content=\"\" name=\"description\">\n");
      out.write("\n");
      out.write("<!-- Favicon -->\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/favicon.icon\" rel=\"icon\">\n");
      out.write("\n");
      out.write("<!-- Google Web Fonts -->\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@600&family=Lobster+Two:wght@700&display=swap\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Icon Font Stylesheet -->\n");
      out.write("<link\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Libraries Stylesheet -->\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/animate/animate.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/owlcarousel/assets/owl.carousel.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Customized Bootstrap Stylesheet -->\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Template Stylesheet -->\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"container-xxl bg-white p-0\">\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div class=\".d-md-block gap-2\" style=\"margin-top: 6vw;\">\n");
      out.write("\t\t\t<div style=\"float: left; width: 50%;\">\n");
      out.write("\t\t\t\t<button id=\"date\" style=\"width: 100%; height: 10vw; border-radius: 5vw; border: none; background: #fff5f3; font-weight : 550;\"\n");
      out.write("\t\t\t\t\tonclick=\"viewDate()\">날짜별 검사 결과</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div style=\"float: left; width: 50%;\">\n");
      out.write("\t\t\t\t<button id=\"emtion\" style=\"width: 100%; height: 10vw; border-radius: 5vw; border: none; background: #fff5f3; font-weight : 550;\"\n");
      out.write("\t\t\t\t\tonclick=\"viewEmotion()\">감정별 검사 결과</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- 날짜별 검사 내용 시작 -->\n");
      out.write("\n");
      out.write("\t\t<div class=\"container\" id=\"dateView\" style=\"display: block;\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 col-12\">\n");
      out.write("\t\t\t\t\t<div class=\"pb-5 mb-5\">\n");
      out.write("\t\t\t\t\t\t<div class=\"section-title-wrap mb-4\" style=\"margin-top: 6vw;\">\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"section-title text-center\">날짜별 검사 결과</h1>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"section-title-wrap mb-4\">\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"section-title text-center\">감정 그래프</h4>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"idCheck\">\n");
      out.write("\t\t\t\t\t\t<!-- 날짜선택 -->\n");
      out.write("\t\t\t\t\t\t<label for=\"dateSelect\">검사 날짜 선택:</label> <select name=\"date\"\n");
      out.write("\t\t\t\t\t\t\tid=\"dateSelect\" onchange=\"changeDate()\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">--검사 날짜를 선택해주세요--</option>\n");
      out.write("\t\t\t\t\t\t\t<option id=\"result_date\"></option>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"bg-light rounded\">\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width: 100%; height: 100%;\">\n");
      out.write("\t<div id=\"resetChart\">\n");
      out.write("\t\n");
      out.write("\t\t\t\t\t\t<!--차트가 그려질 부분-->\n");
      out.write("\t\t\t\t\t\t\t<canvas id=\"myChart\" width=\"100%\" height=\"130%\" margin-left=\"15px\" padding-left=\"25px\"></canvas>\n");
      out.write("\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 col-12 mx-auto\">\n");
      out.write("\t\t\t\t\t<div class=\"pb-5 mb-5\">\n");
      out.write("\t\t\t\t\t<h4 class=\"section-title text-center\">검사 결과</h4>\n");
      out.write("\t\t\t\t\t\t<div class=\"testimonial-item bg-light rounded p-5\">\n");
      out.write("\t\t\t\t\t\t\t<p id=\"result_c_text\" style=\"font-size:25px;\">\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<!-- test용 시작-->\n");
      out.write("\t\t\t\t\t\t<div class=\"testimonial-item bg-light rounded p-5\">\n");
      out.write("\t\t\t\t\t\t\t<p id=\"result_o_text\" style=\"font-size:25px;\"></p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 col-12 mx-auto\">\n");
      out.write("\t\t\t\t\t<div class=\"pb-5 mb-5\">\n");
      out.write("\t\t\t\t\t\t<div class=\"section-title-wrap mb-4\">\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"section-title text-center\">지도 방향</h4>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"testimonial-item bg-light rounded p-5\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<p id=\"result_direction\" style=\"font-size: 25px\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<!-- <div class=\"col-lg-12 col-12\">\n");
      out.write("\t\t\t\t<div class=\"section-title-wrap mb-5\">\n");
      out.write("\t\t\t\t\t<h4 class=\"section-title\">이런 콘텐츠는 어때요?</h4>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div> -->\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-6 col-12 mb-4 mb-lg-0\">\n");
      out.write("\t\t\t\t<div class=\"team-thumb bg-white shadow-lg\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<h4 class=\"mb-2\">1번</h4>\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t<div class=\"team-info\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/oh.png\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100%; height: auto;\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"verified-image img-fluid\" alt=\"\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-6 col-12 mb-4 mb-lg-0\">\n");
      out.write("\t\t\t\t<div class=\"team-thumb bg-white shadow-lg\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"team-info\">\n");
      out.write("\t\t\t\t\t\t<h4 class=\"mb-2\">2번</h4>\n");
      out.write("\t\t\t\t\t\t<br> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/why.png\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100%; height: auto;\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"verified-image img-fluid\" alt=\"\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- 날짜별 검사 내용 끝 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!-- 감정별 검사 내용 시작 -->\n");
      out.write("\n");
      out.write("\t\t<div class=\"container\" id=\"emotionView\" style=\"display: none;\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 col-12\">\n");
      out.write("\t\t\t\t\t<div class=\"pb-5 mb-5\">\n");
      out.write("\t\t\t\t\t\t<div class=\"section-title-wrap mb-4\" style=\"margin-top: 6vw;\">\n");
      out.write("\t\t\t\t\t\t\t<h1 class=\"section-title text-center\">감정별 검사 결과</h1>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"section-title-wrap mb-4\">\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"section-title text-center\">감정 그래프</h4>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"e_idCheck\">\n");
      out.write("\t\t\t\t\t\t<!-- 날짜선택 -->\n");
      out.write("\t\t\t\t\t\t<label for=\"emotionSelect\">감정 선택:</label> \n");
      out.write("\t\t\t\t\t\t<select name=\"emotion\" id=\"emotionSelect\" onchange=\"changeEmotion()\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">--감정을 선택해주세요--</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"result_aggressive\" id=\"e_result_aggressive\">공격성</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"result_social_anxiety\" id=\"e_result_social_anxiety\">사회불안</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"result_depressed\" id=\"e_result_depressed\">우울</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"result_avpd\" id=\"e_result_avpd\">대인회피</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"result_self_esteem\" id=\"e_result_self_esteem\">자존감</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"result_emotional_instability\"\n");
      out.write("\t\t\t\t\t\t\t\tid=\"e_result_emotional_instability\">정서불안</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"result_deprivation\" id=\"e_result_deprivation\">애정결핍</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"result_inferiority\" id=\"e_result_inferiority\">열등감</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"result_regression\" id=\"e_result_regression\">퇴행</option>\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"bg-light rounded\">\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width: 100%; height: 100%;\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"e_resetChart\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--차트가 그려질 부분-->\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas id=\"e_myChart\" width=\"300px\" height=\"100%\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmargin-left=\"15px\" padding-left=\"25px\"></canvas>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-lg-12 col-12\">\n");
      out.write("\t\t\t\t<div class=\"section-title-wrap mb-5\">\n");
      out.write("\t\t\t\t\t<h4 class=\"section-title\">이런 콘텐츠는 어때요?</h4>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-6 col-12 mb-4 mb-lg-0\">\n");
      out.write("\t\t\t\t<div class=\"team-thumb bg-white shadow-lg\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<h4 class=\"mb-2\">1번</h4>\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t<div class=\"team-info\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/oh.png\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100%; height: auto;\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"verified-image img-fluid\" alt=\"\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-6 col-12 mb-4 mb-lg-0\">\n");
      out.write("\t\t\t\t<div class=\"team-thumb bg-white shadow-lg\">\n");
      out.write("\t\t\t\t\t<!-- <img src=\"images/profile/handsome-asian-man-listening-music-through-headphones.jpg\"\n");
      out.write("                                class=\"about-image img-fluid\" alt=\"\"> -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"team-info\">\n");
      out.write("\t\t\t\t\t\t<h4 class=\"mb-2\">2번</h4>\n");
      out.write("\t\t\t\t\t\t<br> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/why.png\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 100%; height: auto;\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"verified-image img-fluid\" alt=\"\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- <span class=\"badge\">Creative</span>\n");
      out.write("\n");
      out.write("                                <span class=\"badge\">Design</span> -->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- 감정별 검사 내용 끝 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/wow/wow.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/easing/easing.min.js\"></script>\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/waypoints/waypoints.min.js\"></script>\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/owlcarousel/owl.carousel.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<!-- Template Javascript -->\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\n");
      out.write("\n");
      out.write("\t<!-- Chart.js 불러오기 -->\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<!-- Chart 내용 Javascript -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("        \n");
      out.write("    \t$(document).ready(function() {\n");
      out.write("    \t\tuser_id = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("    \t\tconsole.log(user_id);\n");
      out.write("    \t\tloadResult(user_id);\t\n");
      out.write("    \t\t});\n");
      out.write("        \n");
      out.write("        /* JSON형태로 사용자 검사 결과 받아오는 함수 */\n");
      out.write("    \tfunction loadResult(user_id) {\n");
      out.write("    \t\t$.ajax({\n");
      out.write("    \t\t\turl : \"resultList.do\",\n");
      out.write("    \t\t\ttype : \"get\",\n");
      out.write("    \t\t\tdataType : \"json\",\n");
      out.write("    \t\t\tsuccess : makeSelect, /* callback 함수 요청되고나서 실행하는 함수*/\n");
      out.write("    \t\t\terror : function() {\n");
      out.write("    \t\t\t\talert(\"검색된 검사 결과가 없습니다. 심리검사를 진행해주세요\");\n");
      out.write("    \t\t\t}\n");
      out.write("    \t\t});\n");
      out.write("    \t}\n");
      out.write("        \n");
      out.write("    \t/* 셀렉트에 사용자가 실시했던 검사날짜에 따른 option 추가 */\n");
      out.write("        function makeSelect(data){\n");
      out.write("        \tvar listHtml = \"<option>--검사 날짜를 선택해주세요--</option>\";\n");
      out.write("\t\t\tconsole.log(\"makeselect실행완료\")\n");
      out.write("        \t$.each(data,function(index, obj){\n");
      out.write("        \t\tlistHtml+=\"<option value='\"+(obj.result_date)+\"'>\"+(obj.result_date)+\"</option>\";\n");
      out.write("        \t\t$(\"#dateSelect\").html(listHtml);\n");
      out.write("        \t});\n");
      out.write("        \t  \t\n");
      out.write("        };\n");
      out.write("        \n");
      out.write("    \tfunction changeDate(){\n");
      out.write("    \t\t$.ajax({\n");
      out.write("    \t\t\turl : \"resultList.do\",\n");
      out.write("    \t\t\ttype:\"get\",\n");
      out.write("    \t\t\tdataType : \"json\",\n");
      out.write("    \t\t\tsuccess : function(result){\n");
      out.write("    \t\t\t\tconsole.log(result);\n");
      out.write("    \t\t\t\tvar result_date= document.getElementById('dateSelect').value;\n");
      out.write("    \t\t\t\tfor (var i = 0 ; i< result.length ; i++ ){\n");
      out.write("    \t\t\t\t\tvar tf = result[i].result_date\n");
      out.write("    \t\t\t\t\tif(result_date == tf){\n");
      out.write("    \t\t\t\t\t\tindex = i;\n");
      out.write("    \t\t\t\t\t}\n");
      out.write("    \t\t\t\t}\n");
      out.write("    \t\t\t\t\n");
      out.write("    \t\t\t\tvar result_aggressive = result[index].result_aggressive;\n");
      out.write("    \t    \t\tvar result_social_anxiety = result[index].result_social_anxiety;\n");
      out.write("    \t    \t\tvar result_depressed = result[index].result_depressed;\n");
      out.write("    \t    \t\tvar result_avpd = result[index].result_avpd;\n");
      out.write("    \t    \t\tvar result_self_esteem = result[index].result_self_esteem;\n");
      out.write("    \t    \t\tvar result_emotional_instability = result[index].result_emotional_instability;\n");
      out.write("    \t    \t\tvar result_deprivation =result[index].result_deprivation;\n");
      out.write("    \t    \t\tvar result_inferiority =result[index].result_inferiority;\n");
      out.write("    \t    \t\tvar result_regression = result[index].result_regression;\n");
      out.write("\t\t\t\t\tvar result_o_text = result[index].result_o_text.replaceAll('\\\\><strong>', 'class=\"title\" onClick=\"showContent(this.id)\"><strong>▸').replaceAll('\\t', 'style=\"display : none;\"');\n");
      out.write("\t\t\t\t\tvar result_c_text = result[index].result_c_text.replaceAll('\\\\><strong>', 'class=\"title\" onClick=\"showContent(this.id)\"><strong>▸').replaceAll('\\t', 'style=\"display : none;\"');\n");
      out.write("\t\t\t\t\tvar result_c_text2 = result[index].result_c_text2.replaceAll('\\\\><strong>', 'class=\"title\" onClick=\"showContent(this.id)\"><strong>▸').replaceAll('\\t', 'style=\"display : none;\"');\n");
      out.write("\t\t\t\t\tvar result_direction = result[index].result_direction.replaceAll('\\n', '</p><p>');\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tif(result[index].cate_seq === 1) {\n");
      out.write("    \t\t\t\t\tresult_aggressive = (result[index].result_aggressive / 9 * 100).toFixed(1);\n");
      out.write("        \t    \t\tresult_social_anxiety = (result[index].result_social_anxiety / 12 * 100).toFixed(1);\n");
      out.write("        \t    \t\tresult_depressed = (result[index].result_depressed / 18 * 100).toFixed(1);\n");
      out.write("        \t    \t\tresult_avpd = (result[index].result_avpd / 8 * 100).toFixed(1);\n");
      out.write("        \t    \t\tresult_self_esteem = (result[index].result_self_esteem / 29 * 100).toFixed(1);\n");
      out.write("        \t    \t\tresult_emotional_instability = (result[index].result_emotional_instability / 24 * 100).toFixed(1);\n");
      out.write("        \t    \t\tresult_deprivation = (result[index].result_deprivation / 13 * 100).toFixed(1);\n");
      out.write("        \t    \t\tresult_inferiority = (result[index].result_inferiority / 16 * 100).toFixed(1);\n");
      out.write("        \t    \t\tresult_regression = (result[index].result_regression / 11 * 100).toFixed(1);\n");
      out.write("    \t\t\t\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t/* $('#result_o_text').text(result_o_text);\n");
      out.write("\t\t\t\t\t$('result_direction').text(result_direction); */\n");
      out.write("\t\t\t\t\tdocument.getElementById('result_o_text').innerHTML = result_o_text;\n");
      out.write("\t\t\t\t\tdocument.getElementById('result_c_text').innerHTML = result_c_text + result_c_text2;\n");
      out.write("\t\t\t\t\tdocument.getElementById('result_direction').innerHTML = result_direction;\n");
      out.write("\t\t\t\t\tdocument.getElementById('resetChart').innerHTML = \"\"; \n");
      out.write("\t\t\t\t\tdocument.getElementById('resetChart').innerHTML = \"<canvas id='myChart' width='100%' height='100%' margin-left='15px' padding-left='25px'></canvas>\"; \n");
      out.write("\t\t\t\t\t\n");
      out.write("    \t            var context = document.getElementById('myChart').getContext('2d');\n");
      out.write("    \t            var myChart = new Chart(context, {\n");
      out.write("    \t                type: 'bar', // 차트의 형태\n");
      out.write("    \t                data: { // 차트에 들어갈 데이터\n");
      out.write("    \t                    labels: [\n");
      out.write("    \t                        //x 축\n");
      out.write("    \t                        '공격성','사회불안','우울','대인회피','자존감','정서불안','애정결핍','열등감','퇴행'\n");
      out.write("    \t                    ],\n");
      out.write("    \t                    datasets: [\n");
      out.write("    \t                        { //데이터\n");
      out.write("    \t                            label: '심리검사 결과(%)', //차트 제목\n");
      out.write("    \t                            fill: false, // line 형태일 때, 선 안쪽을 채우는지 안채우는지\n");
      out.write("    \t                            data: [\n");
      out.write("    \t                            \tresult_aggressive,result_social_anxiety,result_depressed,result_avpd,result_self_esteem,result_emotional_instability,result_deprivation,result_inferiority,result_regression //x축 label에 대응되는 데이터 값\n");
      out.write("    \t                            ],\n");
      out.write("    \t                            backgroundColor: [\n");
      out.write("    \t                                //색상\n");
      out.write("    \t                                'rgba(255, 99, 132, 0.2)',\n");
      out.write("    \t                                'rgba(54, 162, 235, 0.2)',\n");
      out.write("    \t                                'rgba(255, 206, 86, 0.2)',\n");
      out.write("    \t                                'rgba(75, 192, 192, 0.2)',\n");
      out.write("    \t                                'rgba(153, 102, 255, 0.2)',\n");
      out.write("    \t                                'rgba(255, 159, 64, 0.2)',\n");
      out.write("    \t                                'rgba(255, 99, 132, 0.2)',\n");
      out.write("    \t                                'rgba(54, 162, 235, 0.2)',\n");
      out.write("    \t                                'rgba(255, 206, 86, 0.2)'\n");
      out.write("    \t                            ],\n");
      out.write("    \t                            borderColor: [\n");
      out.write("    \t                                //경계선 색상\n");
      out.write("    \t                                'rgba(255, 99, 132, 1)',\n");
      out.write("    \t                                'rgba(54, 162, 235, 1)',\n");
      out.write("    \t                                'rgba(255, 206, 86, 1)',\n");
      out.write("    \t                                'rgba(75, 192, 192, 1)', \n");
      out.write("    \t                                'rgba(153, 102, 255, 1)',\n");
      out.write("    \t                                'rgba(255, 159, 64, 1)',\n");
      out.write("    \t                                'rgba(255, 99, 132, 1)',\n");
      out.write("    \t                                'rgba(54, 162, 235, 1)',\n");
      out.write("    \t                                'rgba(255, 206, 86, 1)'\n");
      out.write("    \t                            ],\n");
      out.write("    \t                            borderWidth: 1 //경계선 굵기\n");
      out.write("    \t                        }/* ,\n");
      out.write("    \t                        {\n");
      out.write("    \t                            label: 'test2',\n");
      out.write("    \t                            fill: false,\n");
      out.write("    \t                            data: [\n");
      out.write("    \t                                8, 34, 12, 24\n");
      out.write("    \t                            ],\n");
      out.write("    \t                            backgroundColor: 'rgb(157, 109, 12)',\n");
      out.write("    \t                            borderColor: 'rgb(157, 109, 12)'\n");
      out.write("    \t                        } */\n");
      out.write("    \t                    ]\n");
      out.write("    \t                },\n");
      out.write("    \t                options: {\n");
      out.write("    \t                    scales: {\n");
      out.write("    \t                        yAxes: [\n");
      out.write("    \t                            {\n");
      out.write("    \t                            \tticks: {\n");
      out.write("    \t                            \t\t/* y축 설정 변경 */\n");
      out.write("    \t            \t\t\t\t\t\tmin: 0,\n");
      out.write("    \t            \t\t\t\t\t\tmax: 100,\n");
      out.write("    \t            \t\t\t\t\t\tstepSize : 10,\n");
      out.write("    \t            \t\t\t\t\t\tfontSize : 14,\n");
      out.write("    \t            \t\t\t\t\t\t\n");
      out.write("    \t            \t\t\t\t\t\t}\n");
      out.write("    \t                            }\n");
      out.write("    \t                        ]\n");
      out.write("    \t                    }\n");
      out.write("    \t                }\n");
      out.write("    \t            });\n");
      out.write("    \t            \t\n");
      out.write("    \t            \n");
      out.write("    \t            }\n");
      out.write("    \t    \t\t\n");
      out.write("    \t    \t\t\n");
      out.write("    \t\t\t,error : function(){\n");
      out.write("    \t\t\t\talert(\"error\");\n");
      out.write("    \t\t\t}\n");
      out.write("    \t\t});\n");
      out.write("    \t}\n");
      out.write("    \t\n");
      out.write("    \t/* 날짜별 데이터 보기 */\n");
      out.write("    \tfunction viewDate(){\n");
      out.write("    \t\tconsole.log(\"viewDate잘됨\");\n");
      out.write("    \t\t$('#dateView').css('display','block');\n");
      out.write("    \t\t$('#emotionView').css('display','none');\n");
      out.write("    \t}\n");
      out.write("    \t\n");
      out.write("    \t/* 감정별 데이터 보기 */\n");
      out.write("\t\tfunction viewEmotion(){\n");
      out.write("    \t\tconsole.log(\"viewEmotion잘됨\");\n");
      out.write("    \t\t$('#emotionView').css('display','block');\n");
      out.write("    \t\t$('#dateView').css('display','none');\n");
      out.write("\t\t}\n");
      out.write("    \t\t\n");
      out.write("/* 위쪽 날짜별 데이터 자바 스크립트 */\n");
      out.write("/* 아래쪽 감정별 데이터 자바 스크립트 */    \n");
      out.write("\n");
      out.write("\t       \n");
      out.write("\t       \n");
      out.write("\t       /* JSON형태로 사용자 검사 결과 받아오는 함수 */\n");
      out.write("\n");
      out.write("    \t/* 셀렉트에 사용자가 실시했던 검사날짜에 따른 option 추가 */\n");
      out.write("\n");
      out.write("        \n");
      out.write("    \tfunction changeEmotion(){\n");
      out.write("    \t\t$.ajax({\n");
      out.write("    \t\t\turl : \"resultList.do\",\n");
      out.write("    \t\t\ttype:\"get\",\n");
      out.write("    \t\t\tdataType : \"json\",\n");
      out.write("    \t\t\tsuccess : function(result){\n");
      out.write("    \t\t\t\tvar emotion_Select= document.getElementById('emotionSelect').value;\n");
      out.write("    \t\t\t\tconsole.log(result);\n");
      out.write("    \t\t\t\tconsole.log(emotion_Select);\n");
      out.write("    \t\t\t\t\n");
      out.write("    \t\t\t\tconsole.log(result[1][emotion_Select]);\n");
      out.write("    \t\t\t\tvar date = [];\n");
      out.write("    \t\t\t\tvar emotion = [];\n");
      out.write("\n");
      out.write("\t\t\t\t\tfor(var i = 0; i<result.length;i++){\n");
      out.write("\t\t\t\t\t\tdate.push(result[i].result_date);\n");
      out.write("\t\t\t\t\t\temotion.push(result[i][emotion_Select]);\n");
      out.write("\t\t\t\t\t};\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tconsole.log(date);\n");
      out.write("\t\t\t\t\tconsole.log(emotion);\n");
      out.write("\n");
      out.write("\t\t\t\t\tdocument.getElementById('e_resetChart').innerHTML = \"\"; \n");
      out.write("\t\t\t\t\tdocument.getElementById('e_resetChart').innerHTML = \"<canvas id='e_myChart' width='100%' height='100%' margin-left='15px' padding-left='25px'></canvas>\"; \n");
      out.write("\t\t\t\t\t\n");
      out.write("    \t            var e_context = document.getElementById('e_myChart').getContext('2d');\n");
      out.write("    \t            var e_myChart = new Chart(e_context, {\n");
      out.write("    \t                type: 'line', // 차트의 형태\n");
      out.write("    \t                data: { // 차트에 들어갈 데이터\n");
      out.write("    \t                    labels: \n");
      out.write("    \t                        //x 축\n");
      out.write("    \t                        date\n");
      out.write("    \t                    ,\n");
      out.write("    \t                    datasets: [\n");
      out.write("    \t                        { //데이터\n");
      out.write("    \t                            label: emotion_Select, //차트 제목\n");
      out.write("    \t                            fill: true, // line 형태일 때, 선 안쪽을 채우는지 안채우는지\n");
      out.write("    \t                            data: \n");
      out.write("    \t                            \temotion //x축 label에 대응되는 데이터 값\n");
      out.write("    \t                            ,\n");
      out.write("    \t                            backgroundColor: [\n");
      out.write("    \t                                //색상\n");
      out.write("    \t                                'rgba(255, 99, 132, 0.2)',\n");
      out.write("    \t                                'rgba(54, 162, 235, 0.2)',\n");
      out.write("    \t                                'rgba(255, 206, 86, 0.2)',\n");
      out.write("    \t                                'rgba(75, 192, 192, 0.2)',\n");
      out.write("    \t                                'rgba(153, 102, 255, 0.2)',\n");
      out.write("    \t                                'rgba(255, 159, 64, 0.2)',\n");
      out.write("    \t                                'rgba(255, 99, 132, 0.2)',\n");
      out.write("    \t                                'rgba(54, 162, 235, 0.2)',\n");
      out.write("    \t                                'rgba(255, 206, 86, 0.2)'\n");
      out.write("    \t                            ],\n");
      out.write("    \t                            borderColor: [\n");
      out.write("    \t                                //경계선 색상\n");
      out.write("    \t                                'rgba(255, 99, 132, 1)',\n");
      out.write("    \t                                'rgba(54, 162, 235, 1)',\n");
      out.write("    \t                                'rgba(255, 206, 86, 1)',\n");
      out.write("    \t                                'rgba(75, 192, 192, 1)', \n");
      out.write("    \t                                'rgba(153, 102, 255, 1)',\n");
      out.write("    \t                                'rgba(255, 159, 64, 1)',\n");
      out.write("    \t                                'rgba(255, 99, 132, 1)',\n");
      out.write("    \t                                'rgba(54, 162, 235, 1)',\n");
      out.write("    \t                                'rgba(255, 206, 86, 1)'\n");
      out.write("    \t                            ],\n");
      out.write("    \t                            borderWidth: 1 //경계선 굵기\n");
      out.write("    \t                        }/* ,\n");
      out.write("    \t                        {\n");
      out.write("    \t                            label: 'test2',\n");
      out.write("    \t                            fill: false,\n");
      out.write("    \t                            data: [\n");
      out.write("    \t                                8, 34, 12, 24\n");
      out.write("    \t                            ],\n");
      out.write("    \t                            backgroundColor: 'rgb(157, 109, 12)',\n");
      out.write("    \t                            borderColor: 'rgb(157, 109, 12)'\n");
      out.write("    \t                        } */\n");
      out.write("    \t                    ]\n");
      out.write("    \t                },\n");
      out.write("    \t                options: {\n");
      out.write("    \t                    scales: {\n");
      out.write("    \t                        yAxes: [\n");
      out.write("    \t                            {\n");
      out.write("    \t                            \tticks: {\n");
      out.write("    \t                            \t\t/* y축 설정 변경 */\n");
      out.write("    \t            \t\t\t\t\t\tmin: 0,\n");
      out.write("    \t            \t\t\t\t\t\tmax: 20,\n");
      out.write("    \t            \t\t\t\t\t\tstepSize : 2,\n");
      out.write("    \t            \t\t\t\t\t\tfontSize : 14,\n");
      out.write("    \t            \t\t\t\t\t\t\n");
      out.write("    \t            \t\t\t\t\t\t}\n");
      out.write("    \t                            }\n");
      out.write("    \t                        ]\n");
      out.write("    \t                    }\n");
      out.write("    \t                }\n");
      out.write("    \t            });\n");
      out.write("    \t            \t\n");
      out.write("    \t            \n");
      out.write("    \t         \n");
      out.write("    \t            \n");
      out.write("    \t            }\n");
      out.write("    \t    \t\t\n");
      out.write("    \t    \t\t\n");
      out.write("    \t    \t\t\n");
      out.write("    \t    \t\t\n");
      out.write("    \t\t\t\n");
      out.write("    \t\t\t,error : function(){\n");
      out.write("    \t\t\t\talert(\"error\");\n");
      out.write("    \t\t\t}\n");
      out.write("    \t\t});\n");
      out.write("    \t}\n");
      out.write("    \t\n");
      out.write("    \t// p태그에 따른 컨텐츠 더보기 함수\n");
      out.write("    \tfunction showContent(clicked_id) {\n");
      out.write("    \t\tconsole.log(clicked_id);\n");
      out.write("    \t\tvar names = [\"window\", \"door\", \"roof\", \"wall\", \"c_smoke\", \"chimney\", \"sun\", \"aggressive\", \"anxiety\", \"depressed\", \"avpd\", \"esteem\", \"instability\", \"deprivation\", \"inferiority\", \"regression\"];\n");
      out.write("    \t\tvar title = $(\"#\"+clicked_id+\">strong\").text();\n");
      out.write("    \t\tfor(var i = 0; i < names.length; i++) {\n");
      out.write("    \t\t\tif(clicked_id == names[i]) {\n");
      out.write("    \t\t\t\tif( $(\"#\"+names[i]+\"C\").css(\"display\") == \"none\" ) {\n");
      out.write("    \t\t\t\t\t$(\"#\"+names[i]+\"C\").css(\"display\", \"inline-block\");\n");
      out.write("    \t\t\t\t\t$(\"#\"+clicked_id+\">strong\").text(title.replace(\"▸\", \"▾\"));\n");
      out.write("    \t\t\t\t} else {\n");
      out.write("    \t\t\t\t\t$(\"#\"+names[i]+\"C\").css(\"display\", \"none\");\n");
      out.write("    \t\t\t\t\t$(\"#\"+clicked_id+\">strong\").text(title.replace(\"▾\", \"▸\"));\n");
      out.write("    \t\t\t\t}\n");
      out.write("    \t\t\t}\n");
      out.write("    \t\t}\n");
      out.write("    \t}\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        </script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/member/myPage.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/member/myPage.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/myPage.jsp(7,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
